name: 'Sleuth API Deploy Registration'
description: 'Register a deploy via the Sleuth API'
branding:
  icon: codepen
  color: blue
inputs:
  organization-slug:
    description: 'Slug of the organization parent of the affected code deployment'
    required: true
  deployment-slug:
    description: 'Slug of the code deployment'
    required: true
  api-key:
    description: 'Sleuth organization API key'
    required: true
  sha:
    description: 'The git SHA of the deployment'
    required: true
    default: ${{ github.sha }}
  environment:
    description: 'String defining the environment to register the deploy against'
  email:
    description: 'Email address of author'
  ignore-if-duplicate:
    description: 'Will not cause a failure if a deploy already exists'
    default: 'false'
outputs:
  status:
    description: 'Response status code'
runs:
  using: 'node12'
  main: 'dist/index.js'